### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by CTOverton** [NikoTheGreeko/VillageWebsiteDrosia#1]
Here are some items to get started @NikoTheGreeko, when you complete them check the box and @CTOverton in a comment when you are done!

**Learn the basics**

Web dev basics
- [x] html https://www.youtube.com/watch?v=ok-plXXHlWw
- [x] css https://www.youtube.com/watch?v=OEV8gMkCHXQ
- [x] javascript https://www.youtube.com/watch?v=DHjqpvDnNGE

Collaboration basics
- [x] Git https://www.youtube.com/watch?v=hwP7WQkmECE
- [x] Pull Requests (GitHub) https://www.youtube.com/watch?v=8lGpZkjnkt4

---
- [x] #2

**Comment by NikoTheGreeko** [comment]
@CTOverton Finished Part 1!

**Comment by CTOverton** [comment]
Hell yeah! On to step 2 :D
